const bcrypt = require('bcrypt');


const password ="Arpit@123";

// hascode + salt , we will use bcrypt library to convert it intp the hash value
async function Hashing() {
     
    const salt = await bcrypt.genSalt(10); // it is used to generate the salt value which is used to make the hash value more secure and it is a random value which is added to the password before hashing and it is used to prevent the rainbow table attack and it is generated by the bcrypt library and it is a unique value for each password and it is stored in the database along with the hash value to verify the password during login process

    // console.time("hash");  // it is the starting of the time to check the time taken for the hashing process


const hashpass =  await bcrypt.hash(password,salt); 
// console.timeEnd("hash"); // to check the time taken at the end

// console.log(hashpass);

}

Hashing();
// here 10 is the round number of which we used it in the hash code generation , the number of times actually , which is used to make the hash value more secure and bcrypt is the library which is used to convert the password into hash value and means bcrypt helps to add in the password with salt value and then converting it into the hash code
//$2b$10$7gJ08b4AN9L96q0NGIjeXu/Ta9bA7wllfbeXFMaPN6lehBfICchmW // this is the hash value of the password which is generated by the bcrypt library and it is a combination of the password and the salt value and it is a unique value which is generated for each password and it is not possible to reverse the hash value to get the original password and it is used to store the password in the database in a secure way.